# Generated by Django 4.0.2 on 2023-11-14 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='build',
            fields=[
                ('build_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_time', models.DateField(default=datetime.datetime(2023, 11, 14, 12, 26, 34, 433761, tzinfo=utc))),
                ('expiration_time', models.DateField(default=datetime.datetime(2023, 11, 24, 12, 26, 34, 433761, tzinfo=utc))),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('file_loc', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=100)),
                ('image_loc', models.CharField(max_length=1000)),
                ('failed_reason', models.CharField(max_length=500)),
                ('image_name', models.CharField(max_length=100)),
                ('image_tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'build',
            },
        ),
        migrations.CreateModel(
            name='push',
            fields=[
                ('push_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_time', models.DateField(default=datetime.datetime(2023, 11, 14, 12, 26, 34, 435755, tzinfo=utc))),
                ('expiration_time', models.DateField(default=datetime.datetime(2023, 11, 24, 12, 26, 34, 435755, tzinfo=utc))),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('image_loc', models.CharField(max_length=1000)),
                ('failed_reason', models.CharField(max_length=500)),
                ('image_name', models.CharField(max_length=100)),
                ('image_tag', models.CharField(max_length=100)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dockerservice_application.build')),
            ],
            options={
                'db_table': 'push',
            },
        ),
    ]
